language: csharp
script:
  - xbuild /p:Configuration=Debug Ansario.Web.API.sln
#before_install:
#  - sudo apt-get install nunit-console
before_script:
  - nuget restore Ansario.Web.API.sln
#after_script:
#  - nunit-console Tests/bin/Debug/Tests.dll